- name: Removing pre-existing sources.list
  file: path=/etc/apt/sources.list.d/nuage.list state=absent

- name: Create Nuage sources.list
  lineinfile:
    dest: /etc/apt/sources.list.d/nuage.list
    line: "{{ nuage_vrs_debs_repo }} {{ images_dir }}/"
    state: present
    create: yes

- name: Running apt-update
  apt:
    update_cache: yes
  ignore_errors: True

- name: Install python-novaclient
  apt:
    name: "{{ python_novaclient }}"
    state: latest
    force: yes

- name: Install nuage-metadata-agent
  apt:
    name: "{{ nuage_metadata_agent }}"
    state: latest
    force: yes

- shell: cat /etc/nova/nova.conf | grep metadata_proxy_shared_secret | awk '{print $3;}' > "{{ metadata_secret_file }}"

- shell: cat /etc/nova/nova.conf | grep auth_uri | awk '{print $3;}' > "{{ auth_uri_file }}"

- shell: cat /etc/nova/nova.conf | grep my_ip | awk '{print $3;}' > "{{ metadata_ip_file }}"

- shell: cat /etc/nova/nova.conf | grep project_name | awk '{print $3;}' | head -1 > "{{ project_name_file }}"

- shell: grep ^password /etc/nova/nova.conf | awk '{print $3;}' | tail -1 > "{{ nova_password_file }}"

- fetch: src=/root/metadata_ip.txt dest=/root

- fetch: src=/root/secret.txt dest=/root

- fetch: src=/root/nova_password.txt dest=/root

- fetch: src=/root/project_name.txt dest=/root

- fetch: src=/root/auth_uri.txt dest=/root

- name: Create nuage-metadata-agent configuration file
  file: path=/etc/default/nuage-metadata-agent state=touch

- name: Add metadata port
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "METADATA_PORT={{ metadata_port }}"

- name: Add nova metadata ip
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "NOVA_METADATA_IP={{ lookup('file', '/root/compute1/root/metadata_ip.txt') }}"

- name: Add nova metadata port
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "NOVA_METADATA_PORT={{ nova_metadata_port }}"

- name: Add metadata proxy shared secret
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "METADATA_PROXY_SHARED_SECRET={{ lookup('file', '/root/compute1/root/secret.txt') }}"

- name: Add nova client version
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "NOVA_CLIENT_VERSION={{ nova_client_version }}"

- name: Add nova openstack username
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "NOVA_OS_USERNAME={{ nova_os_username }}"

- name: Add nova openstack password
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "NOVA_OS_PASSWORD={{ lookup('file', '/root/compute1/root/nova_password.txt') }}"

- name: Add nova openstack tenant name
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "NOVA_OS_TENANT_NAME={{ lookup('file', '/root/compute1/root/project_name.txt') }}"

- name: Add Nova Openstack auth url
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "NOVA_OS_AUTH_URL={{ lookup('file', '/root/compute1/root/auth_uri.txt') }}/v2.0"

- name: Add Nova API Endpoint type
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "NOVA_API_ENDPOINT_TYPE={{ nova_api_endpoint_type }}"

- name: Add  Nova Region Name
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "NOVA_REGION_NAME={{ nova_region_name }}"

- name: Add Nuage Metadata Agent restart with OVS
  lineinfile:
    dest: /etc/default/nuage-metadata-agent
    line: "NUAGE_METADATA_AGENT_START_WITH_OVS=true"

# Restart Nuage openvswitch-switch
- name: start nuage openvswitch
  service:
    name: "{{ nuage_openvswitch_switch }}"
    state: "restarted"

# Cleanup of unwanted temp files
- shell: rm "{{ metadata_secret_file }}"
 
- shell: rm "{{ auth_uri_file }}"
 
- shell: rm "{{ metadata_ip_file }}"

- shell: rm "{{ project_name_file }}"

- shell: rm "{{ nova_password_file }}"
